### ISSUE TITLE
Error on exporting Users

### ISSUE THREAD

**Issue by sbskamey** [mathetos/export-users-to-csv#28]
Hi, I'm not a developer so I'm hoping this makes sense.

When I export Users, the Export Excel File has multiple lines of messed up users.

I have noticed that these are duplicates and the original user is still also in the Export File too.

Also, the second issue is that some data for some members is not showing, for example date of birth.

I have included a screen grab below.

Please help!

Thanks

Kam

<img width="664" alt="screenshot 2018-12-30 at 10 28 55" src="https://user-images.githubusercontent.com/22370316/50546316-e8c01c80-0c1d-11e9-9cff-1e381abe8570.png">

<img width="219" alt="screenshot 2018-12-30 at 11 08 20" src="https://user-images.githubusercontent.com/22370316/50546665-6cc8d300-0c23-11e9-9e48-5f1c2e5b2787.png">

**Comment by mathetos** [comment]
Hi there,

This is most likely due to your database character set or special characters in your usernames (it looks like you have some international users who might have non-Latin characters in their usernames). 

You can read more about your database character set and how to change it here:
https://codex.wordpress.org/Converting_Database_Character_Sets

Just to confirm that, I'd use the Exporter on your standard Posts or Pages or Media as well and see what the output is there. 

Changing your character set can be a bit tricky, so I'd recommend getting a developer from Coadable to help you with that. 

Lastly, Github is really just for code bugs and fixes. General free support is offered here:
https://wordpress.org/support/plugin/export-users-to-csv

Thanks!
